# Generated by Django 4.2.16 on 2024-10-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(max_length=255)),
                ('intervention_date', models.DateField()),
                ('intervention_notes', models.TextField()),
            ],
        ),
    ]
