# Generated by Django 4.2.16 on 2024-10-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
